# Generated by Django 4.2.7 on 2025-09-27 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
    ]
